In [34]:
import pandas as pd
import numpy as np
import os

train_set = 'train.csv'
test_set = 'test.csv'
output_csv = 'dataset.csv'

In [29]:
df_train = pd.read_csv(train_set)
df_test = pd.read_csv(test_set)

df_train = df_train.drop("Time_taken(min)", axis = 1)

full_dataset = pd.concat([df_train, df_test], ignore_index = True)

full_dataset['Order_Date'] = pd.to_datetime(full_dataset['Order_Date'])    
full_dataset['Time_Orderd'] = pd.to_datetime(full_dataset['Time_Orderd'].str.strip(), errors='coerce').dt.strftime('%H:%M:%S')

full_dataset = full_dataset.sort_values(
    by=['Order_Date', 'Time_Orderd'], 
    ascending=[True, True], 
    na_position='last' 
)
full_dataset

/tmp/ipykernel_8208/1467180942.py:8: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  full_dataset['Order_Date'] = pd.to_datetime(full_dataset['Order_Date'])
/tmp/ipykernel_8208/1467180942.py:9: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  full_dataset['Time_Orderd'] = pd.to_datetime(full_dataset['Time_Orderd'].str.strip(), errors='coerce').dt.strftime('%H:%M:%S')

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City
608,0xd152,BHPRES15DEL03,38,4.8,23.234249,77.434007,23.294249,77.494007,2022-02-11,00:00:00,00:10:00,conditions Fog,Low,1,Meal,scooter,1,No,Urban
24044,0xc401,LUDHRES11DEL02,25,4.6,30.893081,75.821495,30.943081,75.871495,2022-02-11,00:00:00,00:05:00,conditions Sandstorms,Low,1,Snack,scooter,0,No,Metropolitian
29560,0xd300,KOCRES05DEL03,39,4.6,9.970717,76.285447,10.030717,76.345447,2022-02-11,00:00:00,00:05:00,conditions Windy,Low,2,Snack,motorcycle,1,No,Metropolitian
37357,0xc614,DEHRES04DEL03,36,4.9,30.340722,78.060221,30.370722,78.090221,2022-02-11,00:00:00,00:10:00,conditions Sunny,Low,1,Drinks,motorcycle,0,No,Urban
18512,0xcb30,AGRRES08DEL01,22,4.3,27.160934,78.044095,27.170934,78.054095,2022-02-11,08:10:00,08:20:00,conditions Windy,Low,0,Drinks,motorcycle,0,No,Urban
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50508,0xd68,RANCHIRES08DEL01,NaN,NaN,23.353783,85.326967,23.463783,85.436967,2022-04-06,NaN,00:05:00,conditions Windy,Low,1,Snack,scooter,1,No,Urban
51919,0x4258,PUNERES14DEL01,NaN,NaN,18.516216,73.842527,18.626216,73.952527,2022-04-06,NaN,21:20:00,conditions Sunny,Jam,2,Snack,scooter,0,No,Metropolitian
55280,0x4ab,MUMRES16DEL03,NaN,NaN,-19.120083,-72.907385,19.210083,72.997385,2022-04-06,NaN,19:45:00,conditions NaN,NaN,3,Buffet,scooter,2,No,Urban
55415,0x5f3,BANGRES06DEL02,NaN,NaN,-12.979096,77.640625,13.059096,77.720625,2022-04-06,NaN,17:55:00,conditions Sunny,Medium,2,Snack,scooter,1,No,Metropolitian
55894,0x1b4b,RANCHIRES03DEL02,NaN,NaN,0.000000,0.000000,0.080000,0.080000,2022-04-06,NaN,17:15:00,conditions NaN,NaN,3,Buffet,electric_scooter,1,No,Metropolitian

In [30]:
full_dataset.dtypes

ID                                     object
Delivery_person_ID                     object
Delivery_person_Age                    object
Delivery_person_Ratings                object
Restaurant_latitude                   float64
Restaurant_longitude                  float64
Delivery_location_latitude            float64
Delivery_location_longitude           float64
Order_Date                     datetime64[ns]
Time_Orderd                            object
Time_Order_picked                      object
Weatherconditions                      object
Road_traffic_density                   object
Vehicle_condition                       int64
Type_of_order                          object
Type_of_vehicle                        object
multiple_deliveries                    object
Festival                               object
City                                   object
dtype: object

In [31]:
temp_date_order = full_dataset['Order_Date'].astype(str) + " " + full_dataset['Time_Orderd'].astype(str)
full_dataset['Order_DateTime'] = pd.to_datetime(temp_date_order, format='%Y-%m-%d %H:%M:%S', errors = "coerce")

temp_date_picked = full_dataset['Order_Date'].astype(str) + " " + full_dataset['Time_Order_picked'].astype(str)
full_dataset['Picked_Datetime'] = pd.to_datetime(temp_date_picked, format='%Y-%m-%d %H:%M:%S', errors = "coerce")
full_dataset

# temp_time = pd.to_datetime(full_dataset['Time_Order_picked'], format = '%H:%M:%S')
# temp_time

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,...,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Order_DateTime,Picked_Datetime
608,0xd152,BHPRES15DEL03,38,4.8,23.234249,77.434007,23.294249,77.494007,2022-02-11,00:00:00,...,conditions Fog,Low,1,Meal,scooter,1,No,Urban,2022-02-11 00:00:00,2022-02-11 00:10:00
24044,0xc401,LUDHRES11DEL02,25,4.6,30.893081,75.821495,30.943081,75.871495,2022-02-11,00:00:00,...,conditions Sandstorms,Low,1,Snack,scooter,0,No,Metropolitian,2022-02-11 00:00:00,2022-02-11 00:05:00
29560,0xd300,KOCRES05DEL03,39,4.6,9.970717,76.285447,10.030717,76.345447,2022-02-11,00:00:00,...,conditions Windy,Low,2,Snack,motorcycle,1,No,Metropolitian,2022-02-11 00:00:00,2022-02-11 00:05:00
37357,0xc614,DEHRES04DEL03,36,4.9,30.340722,78.060221,30.370722,78.090221,2022-02-11,00:00:00,...,conditions Sunny,Low,1,Drinks,motorcycle,0,No,Urban,2022-02-11 00:00:00,2022-02-11 00:10:00
18512,0xcb30,AGRRES08DEL01,22,4.3,27.160934,78.044095,27.170934,78.054095,2022-02-11,08:10:00,...,conditions Windy,Low,0,Drinks,motorcycle,0,No,Urban,2022-02-11 08:10:00,2022-02-11 08:20:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50508,0xd68,RANCHIRES08DEL01,NaN,NaN,23.353783,85.326967,23.463783,85.436967,2022-04-06,NaN,...,conditions Windy,Low,1,Snack,scooter,1,No,Urban,NaT,2022-04-06 00:05:00
51919,0x4258,PUNERES14DEL01,NaN,NaN,18.516216,73.842527,18.626216,73.952527,2022-04-06,NaN,...,conditions Sunny,Jam,2,Snack,scooter,0,No,Metropolitian,NaT,2022-04-06 21:20:00
55280,0x4ab,MUMRES16DEL03,NaN,NaN,-19.120083,-72.907385,19.210083,72.997385,2022-04-06,NaN,...,conditions NaN,NaN,3,Buffet,scooter,2,No,Urban,NaT,2022-04-06 19:45:00
55415,0x5f3,BANGRES06DEL02,NaN,NaN,-12.979096,77.640625,13.059096,77.720625,2022-04-06,NaN,...,conditions Sunny,Medium,2,Snack,scooter,1,No,Metropolitian,NaT,2022-04-06 17:55:00
55894,0x1b4b,RANCHIRES03DEL02,NaN,NaN,0.000000,0.000000,0.080000,0.080000,2022-04-06,NaN,...,conditions NaN,NaN,3,Buffet,electric_scooter,1,No,Metropolitian,NaT,2022-04-06 17:15:00

In [32]:
print(repr(temp_date.iloc[0]))

'2022-02-11 00:10:00'

In [37]:
random_minutes = np.random.randint(15, 121, size=len(full_dataset))
random_deltas = pd.to_timedelta(random_minutes, unit='m')

full_dataset['Delivered_Datetime'] = full_dataset['Picked_Datetime'] + random_deltas
full_dataset

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,...,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Order_DateTime,Picked_Datetime,Delivered_Datetime
608,0xd152,BHPRES15DEL03,38,4.8,23.234249,77.434007,23.294249,77.494007,2022-02-11,00:00:00,...,Low,1,Meal,scooter,1,No,Urban,2022-02-11 00:00:00,2022-02-11 00:10:00,2022-02-11 00:30:00
24044,0xc401,LUDHRES11DEL02,25,4.6,30.893081,75.821495,30.943081,75.871495,2022-02-11,00:00:00,...,Low,1,Snack,scooter,0,No,Metropolitian,2022-02-11 00:00:00,2022-02-11 00:05:00,2022-02-11 01:07:00
29560,0xd300,KOCRES05DEL03,39,4.6,9.970717,76.285447,10.030717,76.345447,2022-02-11,00:00:00,...,Low,2,Snack,motorcycle,1,No,Metropolitian,2022-02-11 00:00:00,2022-02-11 00:05:00,2022-02-11 01:12:00
37357,0xc614,DEHRES04DEL03,36,4.9,30.340722,78.060221,30.370722,78.090221,2022-02-11,00:00:00,...,Low,1,Drinks,motorcycle,0,No,Urban,2022-02-11 00:00:00,2022-02-11 00:10:00,2022-02-11 01:16:00
18512,0xcb30,AGRRES08DEL01,22,4.3,27.160934,78.044095,27.170934,78.054095,2022-02-11,08:10:00,...,Low,0,Drinks,motorcycle,0,No,Urban,2022-02-11 08:10:00,2022-02-11 08:20:00,2022-02-11 09:59:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50508,0xd68,RANCHIRES08DEL01,NaN,NaN,23.353783,85.326967,23.463783,85.436967,2022-04-06,NaN,...,Low,1,Snack,scooter,1,No,Urban,NaT,2022-04-06 00:05:00,2022-04-06 01:50:00
51919,0x4258,PUNERES14DEL01,NaN,NaN,18.516216,73.842527,18.626216,73.952527,2022-04-06,NaN,...,Jam,2,Snack,scooter,0,No,Metropolitian,NaT,2022-04-06 21:20:00,2022-04-06 21:39:00
55280,0x4ab,MUMRES16DEL03,NaN,NaN,-19.120083,-72.907385,19.210083,72.997385,2022-04-06,NaN,...,NaN,3,Buffet,scooter,2,No,Urban,NaT,2022-04-06 19:45:00,2022-04-06 21:37:00
55415,0x5f3,BANGRES06DEL02,NaN,NaN,-12.979096,77.640625,13.059096,77.720625,2022-04-06,NaN,...,Medium,2,Snack,scooter,1,No,Metropolitian,NaT,2022-04-06 17:55:00,2022-04-06 19:01:00
55894,0x1b4b,RANCHIRES03DEL02,NaN,NaN,0.000000,0.000000,0.080000,0.080000,2022-04-06,NaN,...,NaN,3,Buffet,electric_scooter,1,No,Metropolitian,NaT,2022-04-06 17:15:00,2022-04-06 17:30:00

In [39]:
full_dataset = full_dataset.drop(["Order_Date", "Time_Orderd", "Time_Order_picked"], axis=1)
full_dataset

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Order_DateTime,Picked_Datetime,Delivered_Datetime
608,0xd152,BHPRES15DEL03,38,4.8,23.234249,77.434007,23.294249,77.494007,conditions Fog,Low,1,Meal,scooter,1,No,Urban,2022-02-11 00:00:00,2022-02-11 00:10:00,2022-02-11 00:30:00
24044,0xc401,LUDHRES11DEL02,25,4.6,30.893081,75.821495,30.943081,75.871495,conditions Sandstorms,Low,1,Snack,scooter,0,No,Metropolitian,2022-02-11 00:00:00,2022-02-11 00:05:00,2022-02-11 01:07:00
29560,0xd300,KOCRES05DEL03,39,4.6,9.970717,76.285447,10.030717,76.345447,conditions Windy,Low,2,Snack,motorcycle,1,No,Metropolitian,2022-02-11 00:00:00,2022-02-11 00:05:00,2022-02-11 01:12:00
37357,0xc614,DEHRES04DEL03,36,4.9,30.340722,78.060221,30.370722,78.090221,conditions Sunny,Low,1,Drinks,motorcycle,0,No,Urban,2022-02-11 00:00:00,2022-02-11 00:10:00,2022-02-11 01:16:00
18512,0xcb30,AGRRES08DEL01,22,4.3,27.160934,78.044095,27.170934,78.054095,conditions Windy,Low,0,Drinks,motorcycle,0,No,Urban,2022-02-11 08:10:00,2022-02-11 08:20:00,2022-02-11 09:59:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50508,0xd68,RANCHIRES08DEL01,NaN,NaN,23.353783,85.326967,23.463783,85.436967,conditions Windy,Low,1,Snack,scooter,1,No,Urban,NaT,2022-04-06 00:05:00,2022-04-06 01:50:00
51919,0x4258,PUNERES14DEL01,NaN,NaN,18.516216,73.842527,18.626216,73.952527,conditions Sunny,Jam,2,Snack,scooter,0,No,Metropolitian,NaT,2022-04-06 21:20:00,2022-04-06 21:39:00
55280,0x4ab,MUMRES16DEL03,NaN,NaN,-19.120083,-72.907385,19.210083,72.997385,conditions NaN,NaN,3,Buffet,scooter,2,No,Urban,NaT,2022-04-06 19:45:00,2022-04-06 21:37:00
55415,0x5f3,BANGRES06DEL02,NaN,NaN,-12.979096,77.640625,13.059096,77.720625,conditions Sunny,Medium,2,Snack,scooter,1,No,Metropolitian,NaT,2022-04-06 17:55:00,2022-04-06 19:01:00
55894,0x1b4b,RANCHIRES03DEL02,NaN,NaN,0.000000,0.000000,0.080000,0.080000,conditions NaN,NaN,3,Buffet,electric_scooter,1,No,Metropolitian,NaT,2022-04-06 17:15:00,2022-04-06 17:30:00

In [40]:
df = pd.read_csv("dataset.csv")
df

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Order_DateTime,Picked_Datetime,Delivered_Datetime
0,0xd152,BHPRES15DEL03,38,4.8,23.234249,77.434007,23.294249,77.494007,conditions Fog,Low,1,Meal,scooter,1,No,Urban,2022-02-11 00:00:00,2022-02-11 00:10:00,2022-02-11 01:35:00
1,0xc401,LUDHRES11DEL02,25,4.6,30.893081,75.821495,30.943081,75.871495,conditions Sandstorms,Low,1,Snack,scooter,0,No,Metropolitian,2022-02-11 00:00:00,2022-02-11 00:05:00,2022-02-11 00:25:00
2,0xd300,KOCRES05DEL03,39,4.6,9.970717,76.285447,10.030717,76.345447,conditions Windy,Low,2,Snack,motorcycle,1,No,Metropolitian,2022-02-11 00:00:00,2022-02-11 00:05:00,2022-02-11 01:35:00
3,0xc614,DEHRES04DEL03,36,4.9,30.340722,78.060221,30.370722,78.090221,conditions Sunny,Low,1,Drinks,motorcycle,0,No,Urban,2022-02-11 00:00:00,2022-02-11 00:10:00,2022-02-11 01:55:00
4,0xcb30,AGRRES08DEL01,22,4.3,27.160934,78.044095,27.170934,78.054095,conditions Windy,Low,0,Drinks,motorcycle,0,No,Urban,2022-02-11 08:10:00,2022-02-11 08:20:00,2022-02-11 09:32:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56987,0xd68,RANCHIRES08DEL01,NaN,NaN,23.353783,85.326967,23.463783,85.436967,conditions Windy,Low,1,Snack,scooter,1,No,Urban,NaN,2022-04-06 00:05:00,2022-04-06 01:48:00
56988,0x4258,PUNERES14DEL01,NaN,NaN,18.516216,73.842527,18.626216,73.952527,conditions Sunny,Jam,2,Snack,scooter,0,No,Metropolitian,NaN,2022-04-06 21:20:00,2022-04-06 22:43:00
56989,0x4ab,MUMRES16DEL03,NaN,NaN,-19.120083,-72.907385,19.210083,72.997385,conditions NaN,NaN,3,Buffet,scooter,2,No,Urban,NaN,2022-04-06 19:45:00,2022-04-06 21:26:00
56990,0x5f3,BANGRES06DEL02,NaN,NaN,-12.979096,77.640625,13.059096,77.720625,conditions Sunny,Medium,2,Snack,scooter,1,No,Metropolitian,NaN,2022-04-06 17:55:00,2022-04-06 18:18:00
56991,0x1b4b,RANCHIRES03DEL02,NaN,NaN,0.000000,0.000000,0.080000,0.080000,conditions NaN,NaN,3,Buffet,electric_scooter,1,No,Metropolitian,NaN,2022-04-06 17:15:00,2022-04-06 18:30:00